services:
  - type: web
    name: engboost-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production
